begin;

-- Finished history uses the same session/subject/segments shape as snapshot.
-- [p_from, p_to) selects by actual work overlap, but returns ALL segments so
-- the client can clip them to its own absolute week boundaries.
create function public.study_session_history(
    p_from timestamptz default null, p_to timestamptz default null,
    p_limit integer default 100, p_offset integer default 0)
returns jsonb language plpgsql security invoker set search_path = '' as $$
declare
    v_result jsonb;
begin
    if auth.uid() is null then raise exception 'Authentication required' using errcode = '42501'; end if;
    if (p_from is null) <> (p_to is null) or
        (p_from is not null and (not isfinite(p_from) or not isfinite(p_to) or p_to <= p_from)) then
        raise exception 'Provide both finite interval boundaries with from < to' using errcode = '22023';
    end if;
    if p_limit is null or p_limit not between 1 and 200 or p_offset is null or p_offset < 0 then
        raise exception 'Limit must be 1..200 and offset must be nonnegative' using errcode = '22023';
    end if;
    perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(auth.uid()::text, 9));
    select coalesce(jsonb_agg(jsonb_build_object(
        'session', jsonb_build_object('id', s.id, 'subject_id', s.subject_id,
            'description', s.description, 'started_at', s.started_at, 'ended_at', s.ended_at),
        'subject', case when subject.id is null then null else jsonb_build_object(
            'id', subject.id, 'name', subject.name, 'code', subject.code,
            'is_archived', subject.is_archived, 'created_at', subject.created_at) end,
        'segments', (select coalesce(jsonb_agg(jsonb_build_object(
            'id', segment.id, 'session_id', segment.session_id,
            'started_at', segment.started_at, 'ended_at', segment.ended_at)
            order by segment.started_at, segment.id), '[]'::jsonb)
            from public.study_session_segments segment
            where segment.session_id = s.id and segment.user_id = auth.uid())
        ) order by s.started_at desc, s.id desc), '[]'::jsonb)
        into v_result
        from (
            select session.* from public.study_sessions session
            where session.user_id = auth.uid() and session.ended_at is not null
                and (p_from is null or exists (
                    select 1 from public.study_session_segments segment
                    where segment.session_id = session.id and segment.user_id = auth.uid()
                        and segment.ended_at > segment.started_at
                        and segment.started_at < p_to and segment.ended_at > p_from
                ))
            order by session.started_at desc, session.id desc
            limit p_limit offset p_offset
        ) s
        left join public.subjects subject on subject.id = s.subject_id and subject.user_id = auth.uid();
    return v_result;
end;
$$;

-- Full replacement is deliberately simpler than trusting client segment IDs.
-- No client user_id/session_id/segment ID is accepted; all ownership comes from
-- auth.uid(), and replacement segment IDs are generated by the database.
create function public.study_session_history_edit(
    p_session_id uuid, p_subject_id uuid, p_description text,
    p_started_at timestamptz, p_ended_at timestamptz, p_segments jsonb)
returns jsonb language plpgsql security invoker set search_path = '' as $$
declare
    v_session public.study_sessions%rowtype;
    v_segment jsonb;
    v_start timestamptz;
    v_end timestamptz;
    v_previous_end timestamptz;
begin
    if auth.uid() is null then raise exception 'Authentication required' using errcode = '42501'; end if;
    -- Same lock and ordering as timer transitions/snapshot: concurrent RPCs
    -- cannot observe or act on a partially corrected session.
    perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(auth.uid()::text, 9));
    select * into v_session from public.study_sessions
        where id = p_session_id and user_id = auth.uid() for update;
    if not found then raise exception 'Session not found' using errcode = '22023'; end if;
    if v_session.ended_at is null then
        raise exception 'Finish the session before editing history' using errcode = '22023';
    end if;
    if p_description is null or char_length(btrim(p_description)) > 500 then
        raise exception 'Description must be text of at most 500 characters' using errcode = '22023';
    end if;
    if p_started_at is null or p_ended_at is null or
        not isfinite(p_started_at) or not isfinite(p_ended_at) or p_ended_at < p_started_at then
        raise exception 'Session needs finite start/end with end >= start' using errcode = '22023';
    end if;
    if p_subject_id is not null then
        -- An archived own subject remains valid for historical corrections.
        perform id from public.subjects where id = p_subject_id and user_id = auth.uid() for share;
        if not found then raise exception 'Own subject required' using errcode = '22023'; end if;
    end if;
    if jsonb_typeof(p_segments) is distinct from 'array' then
        raise exception 'Segments must be an array' using errcode = '22023';
    end if;
    for v_segment in select value from jsonb_array_elements(p_segments) loop
        if jsonb_typeof(v_segment) is distinct from 'object' then
            raise exception 'Each segment must be an object' using errcode = '22023';
        end if;
        if jsonb_typeof(v_segment->'started_at') is distinct from 'string' or
            jsonb_typeof(v_segment->'ended_at') is distinct from 'string' or
            exists (select 1 from jsonb_object_keys(v_segment) as keys(key)
                where key not in ('started_at', 'ended_at')) then
            raise exception 'Segments accept only start/end timestamp strings' using errcode = '22023';
        end if;
        v_start := (v_segment->>'started_at')::timestamptz;
        v_end := (v_segment->>'ended_at')::timestamptz;
        if not isfinite(v_start) or not isfinite(v_end) or v_end < v_start or
            v_start < p_started_at or v_end > p_ended_at or
            (v_previous_end is not null and v_start < v_previous_end) then
            raise exception 'Segments must be closed, ordered, non-overlapping and inside the session' using errcode = '22023';
        end if;
        v_previous_end := v_end;
    end loop;
    -- Validation and all writes are one transaction. Empty arrays represent
    -- zero recorded work; never infer work from the session envelope.
    update public.study_sessions set subject_id = p_subject_id, description = btrim(p_description),
        started_at = p_started_at, ended_at = p_ended_at
        where id = v_session.id and user_id = auth.uid();
    delete from public.study_session_segments where session_id = v_session.id and user_id = auth.uid();
    insert into public.study_session_segments(session_id, user_id, started_at, ended_at)
        select v_session.id, auth.uid(), (value->>'started_at')::timestamptz, (value->>'ended_at')::timestamptz
        from jsonb_array_elements(p_segments);
    return public.study_session_snapshot(v_session.id);
end;
$$;

create function public.study_session_history_delete(p_session_id uuid)
returns uuid language plpgsql security invoker set search_path = '' as $$
declare
    v_session public.study_sessions%rowtype;
begin
    if auth.uid() is null then raise exception 'Authentication required' using errcode = '42501'; end if;
    perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(auth.uid()::text, 9));
    select * into v_session from public.study_sessions
        where id = p_session_id and user_id = auth.uid() for update;
    if not found then raise exception 'Session not found' using errcode = '22023'; end if;
    if v_session.ended_at is null then
        raise exception 'Finish the session before deleting history' using errcode = '22023';
    end if;
    -- Existing same-owner FK deletes segments in this same transaction.
    delete from public.study_sessions where id = v_session.id and user_id = auth.uid();
    return v_session.id;
end;
$$;

revoke all on function public.study_session_history(timestamptz, timestamptz, integer, integer) from public, anon, authenticated;
revoke all on function public.study_session_history_edit(uuid, uuid, text, timestamptz, timestamptz, jsonb) from public, anon, authenticated;
revoke all on function public.study_session_history_delete(uuid) from public, anon, authenticated;
grant execute on function public.study_session_history(timestamptz, timestamptz, integer, integer) to authenticated;
grant execute on function public.study_session_history_edit(uuid, uuid, text, timestamptz, timestamptz, jsonb) to authenticated;
grant execute on function public.study_session_history_delete(uuid) to authenticated;

commit;
